version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - cdk synth -o dist
      - cdk deploy MyCdkProjectStack --require-approval never --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM || exit 1
      
artifacts:
  files:
    - "**/*"
  name: BuildArtifact
